version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    depends_on:
      - mongodb
    command: uvicorn app:app --host ${BACKEND_HOST} --port ${BACKEND_PORT} --reload
    environment:
      - MONGO_URL=${MONGO_URL}
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
